# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.guest =:linux
config.vm.box = "centos/7"
config.vm.hostname  =:"centinflux"
config.vm.post_up_message = "This is a centos influx test box"
config.vm.synced_folder ".","/vagrant", type: "nfs", disable:false
config.vm.provider  "virtualbox" do |v|
v.gui = true
end
config.vm.synced_folder".","/vagrant",:nfs=>true
config.vm.provider :virtualbox do |vb|
#config.vm.network :hostonly, "10.0.2.16"
#vb.customize ["modifyvm", :id, "--natnet1","10.2/16"]
vb.customize ["modifyvm", :id, "--memory", "4096"]
vb.customize ["modifyvm", :id, "--cpus","2"]
vb.customize ["modifyvm", :id, "--hwvirtex","on"]
vb.customize ["modifyvm", :id, "--audio","none"]


config.vm.provision "shell", path: "provision/provision.sh"
end
end
Vagrant::Config.run do |config|
config.vm.network :hostonly, "10.0.2.16"
#vb.customize ["modifyvm", :id, "--natnet1","10.2/16"]
end
